### PR TITLE
Switches to GZip compression

### PR DESCRIPTION
**Pull request by dirkgr**
When this is merged, I'll make the corresponding change in the scholar project.

### CODE REVIEW

**Comment by rodneykinney** [comment]
Instead of changing the compression implementation in code, can we parameterize it so that we don't lose the ability to read old data?

**Comment by dirkgr** [comment]
How do you feel about making it auto detect compression? For downloading, it would try gzip first, then bzip, and then no compression. All new files will be gzip. I think that'll be far easier to use than plumbing through the choice of compressor.

**Comment by rodneykinney** [comment]
Auto-detection would be great, so long as it's backward-compatible.

**Comment by dirkgr** [comment]
This has auto detection, and it handles the artifact names a little different. Now, you don't have to worry about picking the right suffix anymore for your artifact name. The pipeline appends the right suffix automatically. There is a corresponding change in https://github.com/allenai/scholar/pull/2554.

**Comment by rodneykinney** [comment]
LGTM

**Pull request merged**
