### PR TITLE
minor fixup: document complete Producer parametrization.

### PR DESCRIPTION
**Pull request by cristipp**

### CODE REVIEW

**Comment by cristipp** [comment]
A couple more questions: 
- Are there uses of "CachingEnabled", or could we simplify and always enable caching?
- Is there a way to hide the implementation details from the Producer "interface"? For example, as a client of the library I have no idea what am I supposed to do with "get", "persisted", "copy", "createAndTime". They all look like implementation details.

**Comment by jakemannix** [comment]
Regarding implementation details: get() is most certainly not an impl
detail - it's the primary interface to the API!  If you have a handle on a
Producer, this is basically the only thing you'll be calling.  persisted()
is actually an important one as well, as this is the way to _force_
persistence off to e.g. S3.  Not every Producer step would actually do
persisted(), because it may just be intermediate.

This is the API interaction point to demand your particular intermediate
should get really saved (in such a way that the next call to "get()" on a
Producer of this class which has the same signature as this one will end up
only having to load the data from this storage (be it S3 or local or
wherever), and not do any of the "real work" of the create() method).

copy() and createAndTime are indeed pretty internal, and possibly should be
marked private:

On Thu, Mar 12, 2015 at 10:53 AM, cristipp notifications@github.com wrote:

> A couple more questions:
> 
>    -
> 
>    Are there uses of "CachingEnabled", or could we simplify and always
>    enable caching?
>    -
> 
>    Is there a way to hide the implementation details from the Producer
>    "interface"? For example, as a client of the library I have no idea what am
>    I supposed to do with "get", "persisted", "copy", "createAndTime". They all
>    look like implementation details.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/allenai/pipeline/pull/11#issuecomment-78546743.

## 

  -jake

**Comment by cristipp** [comment]
Sure,

**Comment by cristipp** [comment]
<dang, pressed wrong button>

Ok, "get" is how to read the values, sorry about that.

persisted is less clear. We do have an "optionallyPersistRdd" on some other class. Maybe we have others. Would the real "persist" raise its hand?

I'm also a bit unclear why do we need to even create a Producer if we don't persist the data on disk. What's wrong with a plain old Rdd? If Producer (and maybe there are better names) is really about persisting data on disk, then it should happen automagically anyway and I should never have to call "persist". I just make a Producer, and "get" its value: look ma, the data is already on disk.

**Comment by jakemannix** [comment]
In principle, yes, you could operate with just RDD, if your outputs aren't
going to ever be persisted.  In some sense, the Producer is also a logical
unit of work: a nice OO-encapsulation of a set of possibly multiple (RDD,
in the spark case) operations on some inputs, producing deterministic
outputs which you _could_ persist, and using the PipelineBuilder class's
optionallyPersistRdd() you can choose to in a configurable way, which
delegates down to the persist() method, which I guess you can say is lower
level: it allows you to specify the IO format and the path directly.  Maybe
that's your point, that optionallyPersistedRdd() (and optionallyPersist()
for non RDD outputs) is the userland code 99% interface to saving, while
persist() could be private, as it's needed to e.g. wire in protobufs, etc,
but it's not meant to be _often_ used by the consumer.

On Thu, Mar 12, 2015 at 11:14 AM, cristipp notifications@github.com wrote:

> Ok, "get" is how to read the values, sorry about that.
> 
> persisted is less clear. We do have an "optionallyPersistRdd" on some
> other class. Maybe we have others. Would the real "persist" raise its hand?
> 
> I'm also a bit unclear why do we need to even create a Producer if we
> don't persist the data on disk. What's wrong with a plain old Rdd? I
> Producer (and maybe there are better names) is really about persisting data
> on disk, then it should happen automagically anyway and I should never have
> to call "persist". I just make a Producer, and "get" its value: look ma,
> the data is already on disk.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/allenai/pipeline/pull/11#issuecomment-78552672.

## 

  -jake

**Comment by rodneykinney** [comment]
The `create` method should really be protected.  `createAndTime` can be private.

The `persist` method gives low-level control.  You can specify the exact location and format.  The `optionallyPersistRdd` method in `Pipeline` just supplies a location and format that are consistent for all the steps in the pipeline.  This ensures, for example, that all outputs get written to the same directory.

**Comment by rodneykinney** [comment]
Of course there are many cases where you just want to define a function that produces an `RDD` We have many such functions throughout the code.  It's just that if you think you might ever want to persist the output of this function, you can, simply by wrapping that function in  `case class Foo(...) extends Producer[...] with Ai2StepInfo  { def create = ... }` It's very handy to be able to persist certain steps as you're debugging them and then turn off persistence once you feel it's stabilized.

**Comment by cristipp** [comment]
Updated private-ness. Any comments on how/where the "def stepInfo: PipelineStepInfo" is actually used to generate the final location? I'd love to point the reader to the actual code location / documentation for the 99% case.

On persist, it's out-of-scope for this PR. Thank for the feedback tough, it's a fun conversation :)

I somewhat disagree persist gives low-level control. Low-level control is producer.persist(fileSystem, path). The current API is mid-level control, which is worst kind of control. Think middlemen :) Concretely, how'd one use the API to write an Producer under s3://ai2-tmp/data/test-producer/*?

On debug convenience, we're on the same page that helpers are handy. One thing to note, while debugging, I use a lot of println statements, which I take out at PR time. I don't see why we can't do the same for RDD debug one-liners. I can also think of Debug.persist(name, rdd) as an alternate one-liner; I don't care as much about param uniqueness when debugging. The production code should contain Producers if we really intend to persist the output, not if they were debug scaffolding.

**Comment by cristipp** [comment]
@rodneykinney: These are the docs we pair generated. Double-check and merge at your leisure.

Fun additional discussion we've had: It would be great if we had something like:

PersistentRdd(...) {
  def create
  // After this completes, data is on disk one way or another.
  def get = {

  }
}

That is, a Producer[RDD[T]] disguised as a regular RDD, that can be generated as a drop-in decorator for Spark RDDs. The point being potential open source. Help people complete a specific task they don't have an alternative for, within the first 5 minutes and with no hand-holding. Hook them later with more features :)

**Pull request merged**
